services:
  redis:
    image: redis:7-alpine
  eki_ee_bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      - REDIS_HOST=redis
      - BOT_TOKEN=
      - WEBHOOK_ADDRESS=
      - PORT=8083
      - SENTRY_DSN=
      - ENV=
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        compress: "true"
        tag: "{{.ImageName}}"
