version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/msergo/eki_telegram_bot
    steps:
      - setup_remote_docker
      - checkout
      - run: docker build -t msergo/sergo_bot:${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH} .
      - run:
          name: Deploy docker image
          command: |
            if [[ "${CIRCLE_BRANCH}" == "dev" || "${CIRCLE_BRANCH}" == "master" ]]; then
              docker build -t msergo/sergo_bot:${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH} . && \
              docker login -u $DOCKER_USER -p $DOCKER_PASS && \
              docker push msergo/sergo_bot:${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}
            fi
      - run:
          name: Create Sentry release
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
               curl https://sentry.io/api/0/organizations/${SENTRY_ORG}/releases/ \
                  -H 'Authorization: Bearer ${SENTRY_AUTH_TOKEN}' \
                  -H 'Content-Type: application/json' \
                  -d '{"version":"${CIRCLE_SHA1}","ref":"${CIRCLE_PULL_REQUEST}","projects":["${SENTRY_PROJECT}"]}'
            fi
