version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21

    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run build
          command: |
            docker build -t msergo/sergo_bot:${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH} .
      - run:
          name: Push to Docker Hub
          command: |
            if [[ "${CIRCLE_BRANCH}" == "dev" || "${CIRCLE_BRANCH}" == "master" ]]; then
              docker build -t msergo/sergo_bot:${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH} . && \
              docker login -u $DOCKER_USER -p $DOCKER_PASS && \
              docker push msergo/sergo_bot:${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}

              curl https://sentry.io/api/0/organizations/${SENTRY_ORG}/releases/ \
                -H "Authorization: Bearer ${SENTRY_AUTH_TOKEN}" \
                -H "Content-Type: application/json" \
                -d '{"version":"'${CIRCLE_BRANCH}'-'${CIRCLE_SHA1}'","ref":"${CIRCLE_PULL_REQUEST}","projects":["'$SENTRY_PROJECT'"]}'
            fi

workflows:
  default: 
    jobs:
      - build